# **Laptop Price Prediction**

In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/laptop_price.csv')
df.head()

,Brand,Operating System,Processor,RAM Type,RAM Size,Disc Type,Disc Size,Price
0,Lenovo,Windows 11,Intel Core i3,DDR4,8 GB,SSD,256 GB,36990
1,Lenovo,Windows 11,Intel Core i3,DDR4,8 GB,SSD,512 GB,39990
2,ASUS,Windows 11,Intel Core i3,DDR4,8 GB,SSD,512 GB,32990
3,HP,Windows 10,AMD Ryzen 5 Hexa Core,DDR4,8 GB,SSD,512 GB,49990
4,ASUS,MAC,Intel Core i5,DDR4,8 GB,SSD,512 GB,49990

In [ ]:
data=df.copy()

**BRAND**

In [ ]:
def replace_brand(brand):
    if brand=='Lenovo':
        return 1
    elif brand=='ASUS':
        return 2
    elif brand=='HP':
        return 3
    elif brand=='DELL':
        return 4
    elif brand=='RedmiBook':
        return 5
    elif brand=='Realme':
        return 6
    elif brand=='Acer':
        return 7
    elif brand=='MSI':
        return 8
    elif brand=='APPLE':
        return 9
    elif brand=='Infinix':
        return 10
    elif brand=='SAMSUNG':
        return 11
    elif brand=='Ultimus':
        return 12
    elif brand=='Vaio':
        return 13
    elif brand=='GIGABYTE':
        return 14
    elif brand=='Nokia':
        return 15
    elif brand=='ALIENWARE':
        return 16
    
data['Brand']=data['Brand'].apply(replace_brand)

**PROCESSOR**

In [ ]:
data.Processor.nunique()

26

For better Model performance its better to drop this columnas there are 26 categories in Processor column

In [ ]:
data.drop('Processor', axis=1, inplace=True)

**OPERATING SYSTEM**

In [ ]:
def replace_os(os):
    if os =='Windows 11':
        return 1
    elif os =='Windows 10':
        return 2
    elif os =='MAC ':
        return 3
    elif os =='DOS':
        return 4
    elif os =='Chrome':
        return 5
    
data['Operating System']=data['Operating System'].apply(replace_os)

**RAM Type**

In [ ]:
def replace_ram_type(ram_type):
    if ram_type=='DDR4':
        return 1
    elif ram_type=='DDR5':
        return 2
    elif ram_type=='LPDDR4':
        return 3
    elif ram_type=='Unified Memory':
        return 4
    elif ram_type=='LPDDR4X':
        return 5
    elif ram_type=='LPDDR5':
        return 6
    elif ram_type=='LPDDR3':
        return 7
    
data['RAM Type']=data['RAM Type'].apply(replace_ram_type)

**RAM Size**

In [ ]:
def replace_ram_size(ram_size):
    if ram_size=='8 GB':
        return 1
    elif ram_size=='16 GB':
        return 2
    elif ram_size=='4 GB':
        return 3
    elif ram_size=='32 GB':
        return 4

    
data['RAM Size']=data['RAM Size'].apply(replace_ram_size)

**Disc Type**

In [ ]:
def replace_disc_type(disc_type):
    if disc_type=='SSD':
        return 1
    elif disc_type=='HDD':
        return 2
    elif disc_type=='EMMC':
        return 3

    
data['Disc Type']=data['Disc Type'].apply(replace_disc_type)

**Disc Size**

In [ ]:
data['Disc Size'].unique()

array(['256 GB', '512 GB', '1 TB', '128 GB', '64 GB', '32 GB', '2 TB'],
      dtype=object)

In [ ]:
def replace_disc_size(disc_size):
    if disc_size=='256 GB':
        return 1
    elif disc_size=='512 GB':
        return 2
    elif disc_size=='1 TB':
        return 3
    elif disc_size=='128 GB':
        return 4
    elif disc_size=='64 GB':
        return 5
    elif disc_size=='32 GB':
        return 6
    elif disc_size=='2 TB':
        return 7
    
data['Disc Size']=data['Disc Size'].apply(replace_disc_size)

In [ ]:
data.head()

   Brand  Operating System  RAM Type  RAM Size  Disc Type  Disc Size  Price
0      1                 1         1         1          1          1  36990
1      1                 1         1         1          1          2  39990
2      2                 1         1         1          1          2  32990
3      3                 2         1         1          1          2  49990
4      2                 3         1         1          1          2  49990

**MODEL BULDING**

In [ ]:
X=data.drop('Price', axis=1).values
y=data['Price'].values

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std=StandardScaler()
X=std.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('x_train :',x_train.shape)
print('y_train :',y_train.shape)
print('x_test',x_test.shape)
print('y_test',y_test.shape)

x_train : (573, 6)
y_train : (573,)
x_test (144, 6)
y_test (144,)

In [ ]:
# Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse, r2_score

lr=LinearRegression()
lr=lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)


MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

results=pd.DataFrame({"Model":["Linear Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results

               Model           MSE      RMSE  R2 Score
0  Linear Regression  1.594880e+09  39935.95    0.3239

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=100)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Random Forest Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

                      Model           MSE      RMSE  R2 Score
0         Linear Regression  1.594880e+09  39935.95  0.323900
0  Random Forest Regression  6.222820e+08  24945.58  0.790679

In [ ]:
# Gradient boosting
from sklearn.ensemble import GradientBoostingRegressor

grb= GradientBoostingRegressor(n_estimators =100,random_state =0) 
grb.fit(x_train, y_train) 
y_pred = grb.predict(x_test)
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Gradient Boosting Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

                          Model           MSE      RMSE  R2 Score
0             Linear Regression  1.594880e+09  39935.95  0.323900
0      Random Forest Regression  6.222820e+08  24945.58  0.790679
0  Gradient Boosting Regression  5.361670e+08  23155.28  0.828840

In [ ]:
# ADA Boost
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor(n_estimators=100,learning_rate=0.001,random_state=0)
ada.fit(x_train,y_train)
y_pred=ada.predict(x_test)
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["ADA Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

                          Model           MSE      RMSE  R2 Score
0             Linear Regression  1.594880e+09  39935.95  0.323900
0      Random Forest Regression  6.222820e+08  24945.58  0.790679
0  Gradient Boosting Regression  5.361670e+08  23155.28  0.828840
0          ADA Boost Regression  9.889127e+08  31446.98  0.606266

In [ ]:
# XG boost
from xgboost import XGBRegressor

xgb=XGBRegressor(verbosity=0) 
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["XG Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

                          Model           MSE      RMSE  R2 Score
0             Linear Regression  1.594880e+09  39935.95  0.323900
0      Random Forest Regression  6.222820e+08  24945.58  0.790679
0  Gradient Boosting Regression  5.361670e+08  23155.28  0.828840
0          ADA Boost Regression  9.889127e+08  31446.98  0.606266
0           XG Boost Regression  5.701527e+08  23877.87  0.824435

In [ ]:
# Decision Tree
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor(random_state=0)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Decision Tree Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

                          Model           MSE      RMSE  R2 Score
0             Linear Regression  1.594880e+09  39935.95  0.323900
0      Random Forest Regression  6.222820e+08  24945.58  0.790679
0  Gradient Boosting Regression  5.361670e+08  23155.28  0.828840
0          ADA Boost Regression  9.889127e+08  31446.98  0.606266
0           XG Boost Regression  5.701527e+08  23877.87  0.824435
0      Decision Tree Regression  6.609278e+08  25708.52  0.800014

In [ ]:
# XG boost regressor has high R2 score and low RMSE, tune this model and select this to predict the price of Laptop.
xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

print("Mean Squared Error(MSE) : ",(mse(y_pred,y_test)).round(2))
print("Root Mean Squared Error(RMSE) : ",(np.sqrt(mse(y_pred,y_test)).round(2)))
print("R2 Score : ",((r2_score(y_pred, y_test))*100).round(2),'%')

Mean Squared Error(MSE) :  536930927.37
Root Mean Squared Error(RMSE) :  23171.77
R2 Score :  83.12 %

### **Cross Validation to check model performace**

In [ ]:

from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

k=ShuffleSplit(n_splits=20, test_size=0.2, random_state=20)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n\n", score)
print()
print("Average Cross validations Score:", score.mean().round(3))
print("Maximum Cross validations Score:", score.max().round(3))
print("Minimum Cross validations Score:", score.min().round(3))

Cross validations Score:

 [0.83649758 0.86432591 0.856281   0.8667013  0.90547658 0.76531899
 0.81494004 0.80768587 0.66878102 0.87296084 0.77150188 0.73960503
 0.81164907 0.77591398 0.80152525 0.84691267 0.85736544 0.8475034
 0.76904113 0.83504695]

Average Cross validations Score: 0.816
Maximum Cross validations Score: 0.905
Minimum Cross validations Score: 0.669

In [ ]:
# Exporting the model
import pickle
pickle.dump(xgb, open('laptop-price.pkl', 'wb'))